### ISSUE TITLE
Statreset / Objective+timer removed

### ISSUE THREAD

**Issue by byrra** [BONNePlayground/VaultHuntersBetterModelUnlocks#1]
#### Describe the bug
Mod resets any Vault related stats and maybe remove objectives and vault timers
After installing the mod to our server, all stats were reset and people in vaults have no timer and vault objective

#### Steps to reproduce the behavior
It is probably related to a few other performance & extra mods we are using

#### Extra Mods
Logprot, Starterkit, collective, connectivity, starlight, lazydfu, radium, simplebackups, pluto, luckperms, flan, kotlin, observable, bluemap, VH Discordintegration, dcintegration, dynview, vh extra rules, AI improvements, smoothchunk, fastload, incontrol, dicemc, saturn, neruina, fixmyspawnr, alternatecurrent

#### Comment
i dont want you to investigate this as we just removed it but if someone else is having this issue aswell im happy to help troubleshooting.

**Comment by BONNe** [comment]
Which VaultHunters version do you use and which Mod version do you use?

**Comment by BONNe** [comment]
Where these players inside the vault before server restart when mod was added, or mod was already installed and it happened each time on server restart?
Is it possible for you to share the log file?

**Comment by BONNe** [comment]
I made some investigation, and noticed, that the issue is only for players that do not have mod installed on the client.

The issue looks like with the experimantal gear unlock for Cow Vaults.

Under the hood... stats and clock works, but it is just an issue with displaying them, as the mod adds a new `field` for Vaults.
